"""add article content and feed

Revision ID: 38a0931e0141
Revises: b2222269f013
Create Date: 2026-08-03 15:35:04.434193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a0931e0141'
down_revision: Union[str, Sequence[str], None] = 'b2222269f013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('feed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'feeds', ['feed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'feed_id')
    op.drop_column('articles', 'content')
    op.drop_column('articles', 'summary')
    # ### end Alembic commands ###
