"""add source type to feeds

Revision ID: 9eba7ba83165
Revises: 8a96a8ed610d
Create Date: 2026-08-06 16:20:28.637091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9eba7ba83165'
down_revision: Union[str, Sequence[str], None] = '8a96a8ed610d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    source_type = postgresql.ENUM(
        "RSS",
        "CRAWL",
        name="source_type",
    )

    source_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "feeds",
        sa.Column(
            "type",
            source_type,
            nullable=False,
            server_default="RSS",
        ),
    )

    op.alter_column(
        "feeds",
        "type",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'type')
    # ### end Alembic commands ###
